### ISSUE TITLE
add release, downloadable as zip

### ISSUE THREAD

**Issue by hannesdatta** [rgreminger/test-make#3]
Rafael,
let's make it easier for others to download this entire workflow. I think there are some options to download the entire contents as a zip file. We could offer that as an additional link on tilburgsciencehub.com, so ppl can directly download stuff as zip, unzip and go. That would save users the Git trouble (suppose they don't want to go down that road...). Just an idea. Cheers!

**Comment by rgreminger** [comment]
@hannesdatta , thanks for the tip, I made it into a first release.
The download link for the release is:
https://github.com/rgreminger/example-make-workflow/archive/v0.1.zip
Alternatively, you can also use the link that downloads the current version of the master branch: 
https://github.com/rgreminger/example-make-workflow/archive/master.zip 

EDIT: Use the latter link. Will put up v1.0 release once `clean` is fixed
